import { useState } from 'react'
import Head from 'next/head'
import Wrapper from '../components/Layout/Wrapper'
import SearchInput from '../components/SearchInput'
import CryptoTable from '../components/CryptoTable'

export default function Home({data}) {

	const [searchTerm, setSearchTerm] = useState('')

	const filteredData =  data.filter(crypto => {
		return crypto.name.toLowerCase().includes(searchTerm.toLowerCase())
	})

	return (
    	<Wrapper>
    		<Head>
        		<title>Create Next App</title>
        		<meta name="description" content="Generated by create next app" />
        		<link rel="icon" href="/favicon.ico" />
      		</Head>
			<div className="flex items-center justify-center lg:justify-start">
				<SearchInput value={searchTerm} handleChange={(e) => setSearchTerm(e.target.value)}/>
			</div>
			<div className="overflow-x-auto w-full mb-20">
				<CryptoTable cryptoData={filteredData}/>
			</div>
    	</Wrapper>
  )
}



export const getServerSideProps = async () => {
	const res = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false')
	const data = await res.json	()

	return {
		props: {
			data
		}
	}
}
